### ISSUE TITLE
Act on number to left of cursor

### ISSUE THREAD

**Issue by alhirzel** [zsh-vi-more/vi-increment#2]
Thank you so much for writing this!

I was wondering if you could support the following functionality (like vim):

```shell
$ vim file003.txt
```

With the cursor at the beginning of that line, pressing CTRL+A increments the number (i.e. it will "jump to the next number").

An additional idea that would be really handy: if the cursor is at the end of the line, do the same backwards (I wish Vim did this).

**Comment by xPMo** [comment]
Check out the `dev` branch. I think everything is working, and I'll be testing it out for a while before merging.

There may still be bugs.

**Comment by alhirzel** [comment]
Seems to work pretty well, I will continue using it for a bit and let you know if I see anything wrong.

**Comment by xPMo** [comment]
I assume there's no issues, so I'm taking this as a win. `master` is fast-forwarded now.
