### ISSUE TITLE
Ctrl-X doesn't go below 0

### ISSUE THREAD

**Issue by bitkeen** [zsh-vi-more/vi-increment#4]
It just swaps between 0 and 1, but it should go to -1, -2, etc., instead

**Comment by xPMo** [comment]
Hey, can you check out `dev` (in particular `fb8bcc6`), see if it works well for you? I'll merge it into master in a couple of days if you don't see anything wrong with it.

**Comment by bitkeen** [comment]
It works now, except for the case when the number is in the beginning of the line.

In the beginning of the line it will increment `19` to `110`, and decrement `10` to `1-1` (in case cursor is on `0`)

**Comment by xPMo** [comment]
It's actually a problem when the number is the entire line, not just the start (matching goes sour when trying to find the first non-digit). Should work now, added a guard.

**Comment by bitkeen** [comment]
Pulled the dev branch, still have the same problem

**Comment by xPMo** [comment]
Implemented the guards in the wrong order. :neutral_face:

Sorry about the churn, feel free to pull `dev` and test again.

**Comment by bitkeen** [comment]
Works fine now, thanks
